# vim:ft=yaml:
---
version: "3"

services:
  web:
    build:
      context: images/web
    extra_hosts:
      - "web.docker-demo.${DC_DOMAIN:-test}:127.0.0.1"
    expose: ["80"]
    environment:
      VOLUME_UID: ${UID:-1000}
      VOLUME_GID: ${GID:-1000}
      VIRTUAL_HOST: "web.docker-demo.${DC_DOMAIN:-test}"
    volumes:
      - ./data/web:/var/www/localhost
    networks: [default, proxy]
  api:
    build:
      context: images/api
    extra_hosts:
      - "admin.docker-demo.${DC_DOMAIN:-test}:127.0.0.1"
    expose: ["80"]
    environment:
      VOLUME_UID: ${UID:-1000}
      VOLUME_GID: ${GID:-1000}
      VIRTUAL_HOST: "api.docker-demo.${DC_DOMAIN:-test}"
      # ----------------------------------------------------
      DB_NAME: docker_demo
      DB_HOST: db
      DB_USER: docker_demo
      DB_PASSWORD: "docker_demo"
      APP_ENV: dev
    volumes:
      - ./data/api:/var/www/localhost
    networks: [default, proxy]
  db:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: docker_demo
      MYSQL_USER: docker_demo
      MYSQL_DATABASE: docker_demo
    volumes:
      - ./data/db:/data/
      - db-mysql-lib:/var/lib/mysql

networks:
  proxy:
    external: true

volumes:
  db-mysql-lib:

# Local Variables:
# mode: yaml
# End:
